Repository kritikasinghcc/python, pull requests merged in 2021-10, with the labels that each got.

#1 Updated offset and dumper-config
  csgowalls.py
Labels: hacktoberfest-accepted

#2 Added text to speed module
  Text2Speech.py
Labels: hacktoberfest-accepted

#3 Update README.md
  README.md
Labels: enhancement, hacktoberfest-accepted

#4 Implemented MinMax Algo
  MinMaxAlgo.cpp
Labels: good first issue, hacktoberfest-accepted
